name: Jetpack Compose Desktop CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.latest_tag.outputs.tag }}

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: package with Gradle
      run: ./gradlew package

    - name: Get Latest Commit Tag
      id: latest_tag
      run: |
        latest_tag=$(git describe --abbrev=0 --tags)
        echo "tag=$latest_tag" >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: $OUTPUT1
        release_name: Release $OUTPUT1
        body: |
          This is the release for version $OUTPUT1.
        draft: false
        prerelease: false

    - name: Upload MSI
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/Bluebell-$OUTPUT1.msi
        asset_name: Bluebell-$OUTPUT1.msi
        asset_content_type: application/x-msi
