name: Git Lastest tag

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.latest_tag.outputs.tag }}

    steps:
    - uses: actions/checkout@v3

    - name: Get Latest Commit Tag
      id: latest_tag
      run: |
        latest_tag="$(git describe --abbrev=0 --tags)"
        echo "tag={$latest_tag}" >> "$GITHUB_OUTPUT"

  job2:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.output1}}
        run: echo "$OUTPUT1"
