name: Jetpack Compose Desktop CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: package with Gradle
      run: ./gradlew package
    - name: Get Lastest Comit Tag
      id: get_tag
      run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "::set-output name=tag::$latest_tag"
    - name: Release
      id: create_release
      uses: actions/create-release@v1
      with:
       release_name: Release v.${{ steps.get_tag.outputs.tag }}
       draft: false
       prerelease: false
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
