name: Jetpack Compose Desktop CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.latest_tag.outputs.tag }}

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: package with Gradle
      run: ./gradlew package
      
    - name: Set env RELEASE_VERSION
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set env RELEASE_VERSION_NUMBER
      run: |
        VERSION_NUMBER=$(echo $RELEASE_VERSION | sed -e 's/^v//')
        echo "RELEASE_VERSION_NUMBER=${VERSION_NUMBER}" >> $GITHUB_ENV

    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        echo $RELEASE_VERSION_NUMBER
        echo ${{ env.RELEASE_VERSION_NUMBER }}
      

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{  github.ref_name }}
        release_name: Release ${{  github.ref_name }}
        body: |
          This is the release for version${{  github.ref_name }}.
        draft: false
        prerelease: false

    - name: Upload MSI
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/Bluebell-${{  env.RELEASE_VERSION_NUMBER }}.msi
        asset_name: Bluebell-${{  env.RELEASE_VERSION }}.msi
        asset_content_type: application/x-msi
